# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: facepalm 1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "facepalm".freeze
  s.version = "1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Aleksey V. Dmitriev".freeze]
  s.date = "2020-09-30"
  s.email = "rene.dekart@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/.gitkeep",
    "app/controllers/facepalm/endpoint_controller.rb",
    "facepalm.gemspec",
    "init.rb",
    "install",
    "lib/facepalm.rb",
    "lib/facepalm/config.rb",
    "lib/facepalm/engine.rb",
    "lib/facepalm/rack/post_canvas_middleware.rb",
    "lib/facepalm/rails/controller.rb",
    "lib/facepalm/rails/controller/oauth_access.rb",
    "lib/facepalm/rails/controller/redirects.rb",
    "lib/facepalm/rails/controller/url_rewriting.rb",
    "lib/facepalm/rails/helpers.rb",
    "lib/facepalm/rails/helpers/javascript_helper.rb",
    "lib/facepalm/rails/helpers/url_helper.rb",
    "lib/facepalm/routes.rb",
    "lib/facepalm/user.rb"
  ]
  s.homepage = "http://github.com/dekart/facepalm".freeze
  s.rubygems_version = "3.1.2".freeze
  s.summary = "Facebook integration for Rack & Rails application".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<koala>.freeze, ["~> 3.0.0"])
  else
    s.add_dependency(%q<koala>.freeze, ["~> 3.0.0"])
  end
end

